-- ADDITIONAL STRUCTURE QUESTIONS (110 more = 150 total)

INSERT INTO questions (section, part, question_number, question_text, option_a, option_b, option_c, option_d, correct_answer) VALUES

-- More Structure Completion (41-70)
('structure', NULL, 41, 'The first European _____ to the Americas was Christopher Columbus in 1492.', 'sailing', 'who sailed', 'to sail', 'sailed', 'c'),
('structure', NULL, 42, '_____ that the earth revolves around the sun was proposed by Copernicus.', 'The idea', 'It is the idea', 'An idea', 'That idea', 'a'),
('structure', NULL, 43, 'Hurricanes are severe tropical storms _____ over warm ocean waters.', 'which forming', 'that form', 'are forming', 'form', 'b'),
('structure', NULL, 44, '_____ in large quantities in the Middle East and North Africa.', 'Oil is found', 'Oil that is found', 'Oil, which is found', 'Finding oil', 'a'),
('structure', NULL, 45, 'The committee _____ of ten members who meet monthly.', 'is consisting', 'consists', 'consisting', 'has consisted', 'b'),
('structure', NULL, 46, 'New York City, _____ is on the East Coast, is a financial center.', 'which', 'where', 'that', 'it', 'a'),
('structure', NULL, 47, '_____ the first permanent English settlement in America was established.', 'In 1607', 'It was in 1607 that', 'That in 1607', 'Since 1607', 'b'),
('structure', NULL, 48, 'The Wright Brothers made _____ flight in 1903.', 'they made first', 'their first', 'the first their', 'first', 'b'),
('structure', NULL, 49, 'Not until the early nineteenth century _____ the first steam locomotive.', 'was invented', 'invented', 'that invented', 'inventing', 'a'),
('structure', NULL, 50, 'Vitamin C is found _____ in citrus fruits and leafy vegetables.', 'naturally', 'it is natural', 'naturally is', 'being natural', 'a'),
('structure', NULL, 51, '_____ electromagnetic waves were predicted by James Maxwell.', 'That the existence of', 'The existence of', 'It was the existence of', 'When the existence of', 'b'),
('structure', NULL, 52, 'Not only _____ in the field of education but also in social reform.', 'did she work', 'she worked', 'working', 'she did work', 'a'),
('structure', NULL, 53, 'The invention of the printing press _____ the spread of information.', 'it greatly facilitated', 'greatly facilitated', 'greatly that facilitated', 'facilitating greatly', 'b'),
('structure', NULL, 54, '_____ a patent for his telephone in 1876.', 'Alexander Graham Bell received', 'Receiving Alexander Graham Bell', 'Alexander Graham Bell, who received', 'That Alexander Graham Bell received', 'a'),
('structure', NULL, 55, 'In ancient times, _____ was used as a form of money.', 'salt', 'that salt', 'salt that', 'with salt', 'a'),
('structure', NULL, 56, 'The planet Venus is almost _____ Earth in size.', 'as big as', 'so big as', 'big as', 'big than', 'a'),
('structure', NULL, 57, '_____ in the Smithsonian Institution is the original Star-Spangled Banner.', 'Where displayed', 'Displayed', 'Displaying', 'It is displayed', 'b'),
('structure', NULL, 58, 'Lightning is a discharge of electricity _____ between clouds and the ground.', 'occurs', 'occurring', 'that occurring', 'to occur', 'b'),
('structure', NULL, 59, 'Niagara Falls, one of the most famous _____, attracts millions of tourists.', 'waterfalls in North America', 'North American waterfalls', 'waterfall in North America', 'in North America waterfalls', 'a'),
('structure', NULL, 60, '_____ that supplies most of the oxygen in the atmosphere is phytoplankton.', 'The tiny plant life', 'It is the tiny plant life', 'Being the tiny plant life', 'Because of the tiny plant life', 'a'),
('structure', NULL, 61, 'Diamonds are formed under _____ pressure and temperature deep in the Earth.', 'extremely high', 'high extremely', 'they are extremely high', 'extreme of high', 'a'),
('structure', NULL, 62, 'The human brain, _____ weighs about three pounds, contains billions of neurons.', 'which', 'it', 'that it', 'and', 'a'),
('structure', NULL, 63, '_____ many countries use renewable energy sources.', 'In recent years', 'Recent years', 'It is recent years', 'Since recent years that', 'a'),
('structure', NULL, 64, 'Unlike bacteria, viruses cannot _____ without a host cell.', 'reproduce', 'reproducing', 'reproduction', 'to reproduce', 'a'),
('structure', NULL, 65, 'The Louisiana Purchase, _____ in 1803, doubled the size of the United States.', 'which was made', 'was making', 'it made', 'making', 'a'),
('structure', NULL, 66, '_____ causes the seasons is the tilt of Earth''s axis.', 'What', 'That', 'It', 'Which', 'a'),
('structure', NULL, 67, 'George Washington Carver developed hundreds of products _____ from peanuts.', 'they made', 'made', 'were made', 'making them', 'b'),
('structure', NULL, 68, 'The Statue of Liberty, _____ by France, stands in New York Harbor.', 'a gift', 'was a gift', 'which a gift', 'is a gift', 'a'),
('structure', NULL, 69, '_____ cause earthquakes are movements in Earth''s crust.', 'That', 'What', 'Which', 'It', 'b'),
('structure', NULL, 70, 'The Constitution _____ the framework for the United States government.', 'provides', 'providing', 'it provides', 'which providing', 'a'),

-- More Error Identification (71-150)
('structure', NULL, 71, 'The teacher suggested that John studies more for the exam.', 'suggested', 'that', 'studies', 'for', 'c'),
('structure', NULL, 72, 'There is a lot of informations available on the internet.', 'is', 'informations', 'available', 'on', 'b'),
('structure', NULL, 73, 'Each of the students have to submit their assignments by Friday.', 'Each', 'have', 'their', 'by', 'b'),
('structure', NULL, 74, 'The amount of students attending the lecture has increased.', 'amount', 'attending', 'has', 'increased', 'a'),
('structure', NULL, 75, 'Neither the teacher nor the students was aware of the change.', 'Neither', 'nor', 'was', 'of', 'c'),
('structure', NULL, 76, 'If I would have known about the meeting, I would have attended.', 'would have known', 'about', 'would have attended', 'meeting', 'a'),
('structure', NULL, 77, 'The company is looking for someone whom has experience in marketing.', 'looking', 'whom', 'has', 'in', 'b'),
('structure', NULL, 78, 'The museum displays artifacts who date back to ancient times.', 'displays', 'who', 'date', 'to', 'b'),
('structure', NULL, 79, 'By the time we arrived, the concert has already started.', 'By', 'arrived', 'has', 'started', 'c'),
('structure', NULL, 80, 'She speaks English much more fluently than her classmates do it.', 'speaks', 'more fluently', 'than', 'do it', 'd'),
('structure', NULL, 81, 'Despite of the rain, we decided to go hiking in the mountains.', 'Despite of', 'decided', 'to go', 'in', 'a'),
('structure', NULL, 82, 'The research shows that exercise has many beneficially effects on health.', 'shows', 'has', 'beneficially', 'on', 'c'),
('structure', NULL, 83, 'One of the most important invention of the twentieth century was the computer.', 'most', 'invention', 'was', 'the', 'b'),
('structure', NULL, 84, 'The professor explained us the difference between the two theories.', 'explained us', 'difference', 'between', 'theories', 'a'),
('structure', NULL, 85, 'She has been worked at the company for five years now.', 'has', 'been worked', 'at', 'for', 'b'),
('structure', NULL, 86, 'The committee meets every month to discussing current issues.', 'meets', 'every', 'to discussing', 'current', 'c'),
('structure', NULL, 87, 'I enjoy to read books about history and science.', 'enjoy', 'to read', 'about', 'and', 'b'),
('structure', NULL, 88, 'The weather in Florida is much warmer than New York.', 'in', 'is', 'warmer than', 'New York', 'd'),
('structure', NULL, 89, 'He made me to wait for over an hour before the meeting started.', 'made', 'to wait', 'over', 'before', 'b'),
('structure', NULL, 90, 'The book, that I borrowed from the library, is very interesting.', 'book', 'that', 'from', 'interesting', 'b'),
('structure', NULL, 91, 'Almost students in the class passed the final exam.', 'Almost', 'in', 'passed', 'final', 'a'),
('structure', NULL, 92, 'She wishes she can travel to Europe next summer.', 'wishes', 'can', 'to', 'next', 'b'),
('structure', NULL, 93, 'The presentation was interesting, and everybody enjoyed to listen it.', 'was', 'and', 'enjoyed to listen', 'it', 'c'),
('structure', NULL, 94, 'Having studied for the test, the questions were easy for him.', 'Having studied', 'the questions', 'were', 'for', 'b'),
('structure', NULL, 95, 'The manager wants to hire someone which can speak three languages.', 'wants', 'to hire', 'which', 'speak', 'c'),
('structure', NULL, 96, 'She avoided to make the same mistake again by being more careful.', 'avoided to make', 'same', 'by', 'more', 'a'),
('structure', NULL, 97, 'The faster you finish the work, the more soon you can go home.', 'faster', 'finish', 'more soon', 'can go', 'c'),
('structure', NULL, 98, 'He insisted that she comes to the meeting on time.', 'insisted', 'comes', 'to', 'on', 'b'),
('structure', NULL, 99, 'The children were exciting about the upcoming field trip.', 'children', 'exciting', 'upcoming', 'trip', 'b'),
('structure', NULL, 100, 'The newspaper reported that the economy has been improved significantly.', 'reported', 'has been improved', 'significantly', 'economy', 'b'),
('structure', NULL, 101, 'If the weather would be nice tomorrow, we will go to the beach.', 'would be', 'tomorrow', 'will go', 'to', 'a'),
('structure', NULL, 102, 'She looks forward to hear from you soon about the job opportunity.', 'looks', 'to hear', 'from', 'about', 'b'),
('structure', NULL, 103, 'The number of people applying for the position have increased recently.', 'number', 'applying', 'have', 'recently', 'c'),
('structure', NULL, 104, 'They are used to work long hours during the busy season.', 'are', 'to work', 'during', 'busy', 'b'),
('structure', NULL, 105, 'The house is enough big to accommodate all of our guests.', 'is', 'enough big', 'to accommodate', 'all of', 'b'),
('structure', NULL, 106, 'She asked me that could I help her with the project.', 'asked', 'that could I', 'help', 'with', 'b'),
('structure', NULL, 107, 'The documents were sent to the wrong address by mistake accidentally.', 'were sent', 'to', 'by mistake', 'accidentally', 'd'),
('structure', NULL, 108, 'Neither my brother nor my sisters wants to attend the party.', 'Neither', 'nor', 'wants', 'to attend', 'c'),
('structure', NULL, 109, 'The professor recommended that each student buys the required textbook.', 'recommended', 'that', 'buys', 'required', 'c'),
('structure', NULL, 110, 'The company is planning to expand its business into another countries.', 'planning', 'its', 'into', 'another', 'd'),
('structure', NULL, 111, 'Much people believe that technology will solve environmental problems.', 'Much', 'believe', 'will solve', 'problems', 'a'),
('structure', NULL, 112, 'She has difficulty to understand complex mathematical concepts.', 'has', 'to understand', 'complex', 'concepts', 'b'),
('structure', NULL, 113, 'The museum, which was built in 1950, are currently under renovation.', 'which', 'was built', 'are', 'under', 'c'),
('structure', NULL, 114, 'He spent most of his time to prepare for the important presentation.', 'spent', 'to prepare', 'for', 'important', 'b'),
('structure', NULL, 115, 'The professor made clear that attendance is mandatory for all students.', 'made clear', 'that', 'is', 'for', 'a'),
('structure', NULL, 116, 'She was so tired that she could not barely keep her eyes open.', 'was', 'that', 'not barely', 'keep', 'c'),
('structure', NULL, 117, 'The candidate which has the most experience will get the job.', 'candidate', 'which', 'most', 'will get', 'b'),
('structure', NULL, 118, 'Having been told the truth, he felt relief and grateful.', 'Having been told', 'felt', 'relief', 'grateful', 'c'),
('structure', NULL, 119, 'The contract needs to be signed by both party before Friday.', 'needs', 'to be signed', 'party', 'before', 'c'),
('structure', NULL, 120, 'She prefers staying at home than going to crowded places.', 'prefers', 'staying', 'than', 'to', 'c'),
('structure', NULL, 121, 'The government has been made efforts to reduce unemployment rates.', 'has been made', 'to reduce', 'unemployment', 'rates', 'a'),
('structure', NULL, 122, 'Students should avoid to use informal language in academic writing.', 'should', 'to use', 'informal', 'in', 'b'),
('structure', NULL, 123, 'The conference will be held on May and will last three days.', 'will be held', 'on', 'will last', 'three', 'b'),
('structure', NULL, 124, 'He is one of the best player on the team this season.', 'is', 'best', 'player', 'on', 'c'),
('structure', NULL, 125, 'The experiment was conducting under carefully controlled conditions.', 'was conducting', 'under', 'carefully', 'conditions', 'a'),
('structure', NULL, 126, 'She recommended me to take the advanced course instead.', 'recommended me', 'to take', 'advanced', 'instead', 'a'),
('structure', NULL, 127, 'The data shows that temperatures has risen significantly over the decade.', 'shows', 'has risen', 'significantly', 'over', 'b'),
('structure', NULL, 128, 'The professor''s lecture was so bored that many students fell asleep.', 'lecture', 'bored', 'many', 'fell asleep', 'b'),
('structure', NULL, 129, 'She wondered that why the meeting had been canceled so suddenly.', 'wondered', 'that why', 'had been canceled', 'suddenly', 'b'),
('structure', NULL, 130, 'The team has won every game this season, which is impressed everyone.', 'has won', 'every', 'which is impressed', 'everyone', 'c'),
('structure', NULL, 131, 'Between you and I, I think the project needs more funding.', 'Between', 'I', 'think', 'needs', 'b'),
('structure', NULL, 132, 'The report must be completed and submit before the deadline.', 'must', 'be completed', 'submit', 'before', 'c'),
('structure', NULL, 133, 'She is looking for a job where pays well and offers good benefits.', 'looking', 'where', 'pays', 'offers', 'b'),
('structure', NULL, 134, 'The statistics indicates that the economy is improving slowly.', 'statistics', 'indicates', 'is improving', 'slowly', 'b'),
('structure', NULL, 135, 'He decided to quit his job despite he needed the money.', 'decided', 'to quit', 'despite', 'needed', 'c'),
('structure', NULL, 136, 'The new policy will be effect beginning next month.', 'policy', 'will be effect', 'beginning', 'next', 'b'),
('structure', NULL, 137, 'She succeeded in pass the exam after studying very hard.', 'succeeded', 'pass', 'after', 'studying', 'b'),
('structure', NULL, 138, 'The movie was such boring that we left before it ended.', 'was', 'such', 'left', 'ended', 'b'),
('structure', NULL, 139, 'The professor explained the theory clear and with many examples.', 'explained', 'clear', 'with', 'many', 'b'),
('structure', NULL, 140, 'She has visited to Paris several times for business meetings.', 'has', 'visited to', 'several', 'for', 'b'),
('structure', NULL, 141, 'The building is being renovated will reopen next year.', 'building', 'is being renovated', 'will', 'next', 'b'),
('structure', NULL, 142, 'He suggested to go to the beach instead of staying home.', 'suggested to go', 'to', 'instead of', 'staying', 'a'),
('structure', NULL, 143, 'The committee meets once a month for discuss various issues.', 'meets', 'once', 'for discuss', 'various', 'c'),
('structure', NULL, 144, 'She told to me that the meeting had been postponed indefinitely.', 'told to me', 'that', 'had been postponed', 'indefinitely', 'a'),
('structure', NULL, 145, 'The children were not allowed playing in the construction area.', 'were', 'allowed playing', 'in', 'construction', 'b'),
('structure', NULL, 146, 'The price of gas have increased dramatically over the past year.', 'price', 'have', 'dramatically', 'over', 'b'),
('structure', NULL, 147, 'She insisted on to pay for dinner despite our protests.', 'insisted', 'to pay', 'despite', 'our', 'b'),
('structure', NULL, 148, 'The researchers found out that their hypothesis were incorrect.', 'found out', 'that', 'were', 'incorrect', 'c'),
('structure', NULL, 149, 'He is enough experienced to handle this complex situation.', 'is', 'enough experienced', 'to handle', 'complex', 'b'),
('structure', NULL, 150, 'The seminar was attended by more than two hundreds participants.', 'was attended', 'by', 'two hundreds', 'participants', 'c');
