-- ADDITIONAL LISTENING QUESTIONS (150 more = 200 total)
-- Part A: Short Conversations (51-150)

INSERT INTO questions (section, part, question_number, question_text, audio_url, option_a, option_b, option_c, option_d, correct_answer) VALUES

('listening', 1, 51, 'What is the woman''s concern?', NULL, 'The cost of the trip', 'The weather forecast', 'Her exam schedule', 'The transportation', 'c'),
('listening', 1, 52, 'What does the man suggest doing?', NULL, 'Waiting until later', 'Asking for help', 'Starting immediately', 'Changing the plan', 'b'),
('listening', 1, 53, 'Where will the speakers probably go?', NULL, 'To the computer lab', 'To the student center', 'To the gym', 'To the parking lot', 'a'),
('listening', 1, 54, 'What can be inferred about the project?', NULL, 'It is almost finished', 'It is very difficult', 'It requires teamwork', 'It is optional', 'c'),
('listening', 1, 55, 'What does the woman mean?', NULL, 'She is satisfied with her grade', 'She expected a better result', 'She did not study enough', 'She will retake the exam', 'b'),
('listening', 1, 56, 'Why is the man calling?', NULL, 'To cancel an appointment', 'To reschedule a meeting', 'To ask for information', 'To confirm a reservation', 'd'),
('listening', 1, 57, 'What does the professor suggest?', NULL, 'Reading more sources', 'Narrowing the topic', 'Starting over', 'Working with a partner', 'b'),
('listening', 1, 58, 'What is the main problem?', NULL, 'Limited parking spaces', 'High tuition fees', 'Difficult coursework', 'Crowded classrooms', 'a'),
('listening', 1, 59, 'What will the woman do next?', NULL, 'Go to the library', 'Eat dinner', 'Finish her homework', 'Call her parents', 'c'),
('listening', 1, 60, 'What does the man imply about the concert?', NULL, 'It was sold out', 'It was disappointing', 'It was excellent', 'It was canceled', 'c'),
('listening', 1, 61, 'Why does the woman mention her advisor?', NULL, 'To get permission', 'To ask for advice', 'To explain her decision', 'To make an excuse', 'c'),
('listening', 1, 62, 'What are the speakers mainly talking about?', NULL, 'Summer plans', 'Job interviews', 'Graduate school', 'Study abroad programs', 'd'),
('listening', 1, 63, 'What does the man mean when he says "That''s easier said than done"?', NULL, 'He agrees with the suggestion', 'The task is difficult', 'He needs more information', 'The plan is simple', 'b'),
('listening', 1, 64, 'What can be inferred about the woman?', NULL, 'She is a first-year student', 'She is changing majors', 'She is graduating soon', 'She is on academic probation', 'b'),
('listening', 1, 65, 'What does the man suggest the woman do?', NULL, 'Apply for financial aid', 'Get a part-time job', 'Take fewer courses', 'Move off campus', 'b'),
('listening', 1, 66, 'What is the woman''s opinion?', NULL, 'She strongly agrees', 'She partially agrees', 'She disagrees', 'She is uncertain', 'b'),
('listening', 1, 67, 'Why did the man miss the deadline?', NULL, 'He forgot about it', 'He was sick', 'He had technical problems', 'He was traveling', 'c'),
('listening', 1, 68, 'What will happen next week?', NULL, 'A midterm exam', 'A guest lecture', 'A field trip', 'A group presentation', 'b'),
('listening', 1, 69, 'What does the woman imply about the textbook?', NULL, 'It is too expensive', 'It is out of stock', 'It is not required', 'It is very helpful', 'a'),
('listening', 1, 70, 'What is the man''s attitude?', NULL, 'Enthusiastic', 'Frustrated', 'Indifferent', 'Optimistic', 'b'),
('listening', 1, 71, 'What problem does the woman have?', NULL, 'She cannot access the online system', 'She lost her student ID', 'She missed registration', 'She dropped a class by mistake', 'a'),
('listening', 1, 72, 'What does the man recommend?', NULL, 'Contacting IT support', 'Visiting the office', 'Trying again later', 'Using a different computer', 'a'),
('listening', 1, 73, 'What are the speakers discussing?', NULL, 'A scholarship opportunity', 'An internship program', 'A research position', 'A teaching assistant job', 'b'),
('listening', 1, 74, 'Why is the woman concerned?', NULL, 'She lacks experience', 'The deadline passed', 'She does not meet requirements', 'The position is filled', 'c'),
('listening', 1, 75, 'What will the woman probably do?', NULL, 'Submit her application anyway', 'Look for other opportunities', 'Talk to the coordinator', 'Take additional courses', 'c'),
('listening', 1, 76, 'What does the man mean?', NULL, 'He will help later', 'He is too busy now', 'He does not know how', 'He already finished', 'd'),
('listening', 1, 77, 'What is the topic of conversation?', NULL, 'Campus housing', 'Meal plans', 'Transportation options', 'Student activities', 'c'),
('listening', 1, 78, 'What does the woman suggest?', NULL, 'Taking the bus', 'Carpooling', 'Buying a bicycle', 'Walking', 'b'),
('listening', 1, 79, 'What can be inferred about parking?', NULL, 'It is free for students', 'It is very limited', 'It is far from buildings', 'It requires a permit', 'd'),
('listening', 1, 80, 'What will the man do?', NULL, 'Apply for a permit', 'Buy a bus pass', 'Join a carpool', 'Ride a bike', 'c'),
('listening', 1, 81, 'What is the woman''s main concern about the assignment?', NULL, 'Understanding the requirements', 'Finding enough sources', 'Meeting the deadline', 'Working with her group', 'a'),
('listening', 1, 82, 'What does the professor recommend?', NULL, 'Reading the syllabus', 'Attending office hours', 'Forming a study group', 'Using the writing center', 'b'),
('listening', 1, 83, 'What is probably true about the course?', NULL, 'It is very popular', 'It is an elective', 'It is a requirement', 'It is online only', 'c'),
('listening', 1, 84, 'What does the man imply?', NULL, 'The exam will be difficult', 'He is well prepared', 'He needs more time', 'The professor is helpful', 'c'),
('listening', 1, 85, 'What are the speakers planning to do?', NULL, 'Form a study group', 'Review together', 'Share notes', 'All of the above', 'd'),
('listening', 1, 86, 'Where will they meet?', NULL, 'At the library', 'At the cafeteria', 'In the classroom', 'At someone''s apartment', 'a'),
('listening', 1, 87, 'What time will they meet?', NULL, 'In the morning', 'At noon', 'In the afternoon', 'In the evening', 'c'),
('listening', 1, 88, 'What does the woman ask the man to bring?', NULL, 'His textbook', 'His notes', 'His laptop', 'Snacks', 'b'),
('listening', 1, 89, 'What is the man''s problem?', NULL, 'He cannot attend the meeting', 'He lost his notes', 'He does not understand the material', 'He has another commitment', 'd'),
('listening', 1, 90, 'What solution do they agree on?', NULL, 'Meeting at a different time', 'Meeting virtually', 'Skipping the meeting', 'Meeting separately', 'a'),
('listening', 1, 91, 'What is the woman''s major?', NULL, 'Biology', 'Chemistry', 'Engineering', 'Computer Science', 'c'),
('listening', 1, 92, 'Why is she talking to the advisor?', NULL, 'To change her major', 'To add a course', 'To drop a course', 'To plan her schedule', 'd'),
('listening', 1, 93, 'What does the advisor suggest?', NULL, 'Taking a prerequisite first', 'Waiting until next semester', 'Talking to the professor', 'All of the above', 'a'),
('listening', 1, 94, 'What will the woman do next?', NULL, 'Register for the course', 'Check the prerequisites', 'Talk to her parents', 'Change her plan', 'b'),
('listening', 1, 95, 'What are the speakers discussing?', NULL, 'Lab safety', 'Equipment usage', 'Experiment results', 'Lab schedules', 'b'),
('listening', 1, 96, 'What is the man''s concern?', NULL, 'He does not know how to use it', 'It might be broken', 'Someone else is using it', 'He needs permission', 'a'),
('listening', 1, 97, 'What does the woman offer to do?', NULL, 'Show him how', 'Let him borrow hers', 'Ask the professor', 'Find an alternative', 'a'),
('listening', 1, 98, 'When will they meet?', NULL, 'Right now', 'After class', 'Tomorrow', 'Next week', 'b'),
('listening', 1, 99, 'What is the main topic?', NULL, 'A class project', 'A social event', 'A club meeting', 'A volunteer opportunity', 'd'),
('listening', 1, 100, 'What does the man want the woman to do?', NULL, 'Join the organization', 'Donate money', 'Volunteer her time', 'Spread the word', 'c'),

-- Part B: Longer Conversations (101-130)
('listening', 2, 101, 'What is the conversation mainly about?', NULL, 'Course registration problems', 'Graduation requirements', 'Transfer credits', 'Academic advising', 'c'),
('listening', 2, 102, 'What is the student''s situation?', NULL, 'She transferred from another university', 'She changed her major', 'She failed some courses', 'She is graduating early', 'a'),
('listening', 2, 103, 'What does the advisor explain?', NULL, 'How to petition for credit', 'How to retake courses', 'How to change majors', 'How to graduate on time', 'a'),
('listening', 2, 104, 'What must the student do?', NULL, 'Submit course syllabi', 'Take an exam', 'Write a petition', 'Pay a fee', 'a'),
('listening', 2, 105, 'How does the student feel?', NULL, 'Relieved', 'Confused', 'Frustrated', 'Excited', 'b'),
('listening', 2, 106, 'What will the student probably do next?', NULL, 'Gather documents', 'Talk to professors', 'Submit a petition', 'Wait for approval', 'a'),
('listening', 2, 107, 'What is the purpose of the conversation?', NULL, 'To discuss a research opportunity', 'To review an assignment', 'To plan a thesis', 'To prepare for an interview', 'a'),
('listening', 2, 108, 'What is required for the position?', NULL, 'Previous research experience', 'A minimum GPA', 'Professor recommendation', 'All of the above', 'd'),
('listening', 2, 109, 'What does the professor say about the project?', NULL, 'It is fully funded', 'It starts next semester', 'It requires long hours', 'It is very competitive', 'd'),
('listening', 2, 110, 'What must the student submit?', NULL, 'A resume', 'A research proposal', 'Letters of recommendation', 'All of the above', 'd'),
('listening', 2, 111, 'When is the deadline?', NULL, 'Next week', 'End of the month', 'Next semester', 'No specific deadline', 'b'),
('listening', 2, 112, 'What is the student''s main concern?', NULL, 'Time commitment', 'Difficulty level', 'Getting credit', 'Competition', 'a'),
('listening', 2, 113, 'What are the speakers discussing?', NULL, 'Lab equipment', 'Research methods', 'Data analysis', 'Publication process', 'c'),
('listening', 2, 114, 'What problem does the student have?', NULL, 'Insufficient data', 'Conflicting results', 'Software issues', 'Interpretation difficulties', 'd'),
('listening', 2, 115, 'What does the professor suggest?', NULL, 'Collecting more data', 'Using different methods', 'Consulting a statistician', 'Reviewing literature', 'c'),
('listening', 2, 116, 'What will the student do?', NULL, 'Redo the analysis', 'Schedule a consultation', 'Change the methodology', 'Present preliminary findings', 'b'),
('listening', 2, 117, 'What is the main topic of discussion?', NULL, 'Study abroad programs', 'Exchange student experiences', 'International scholarships', 'Language requirements', 'a'),
('listening', 2, 118, 'What is the student interested in?', NULL, 'Studying in Europe', 'Learning a language', 'Earning credits abroad', 'Cultural immersion', 'c'),
('listening', 2, 119, 'What concern does the student express?', NULL, 'Cost', 'Academic level', 'Language barrier', 'Credit transfer', 'd'),
('listening', 2, 120, 'What does the advisor assure?', NULL, 'Financial aid is available', 'Credits will transfer', 'Support is provided', 'Application is easy', 'b'),
('listening', 2, 121, 'What must the student do first?', NULL, 'Apply for the program', 'Get faculty approval', 'Meet GPA requirements', 'Attend an orientation', 'd'),
('listening', 2, 122, 'When should the student apply?', NULL, 'This semester', 'Next semester', 'One year in advance', 'Two years in advance', 'c'),
('listening', 2, 123, 'What are they discussing?', NULL, 'Thesis defense', 'Comprehensive exams', 'Dissertation proposal', 'Qualifying exams', 'b'),
('listening', 2, 124, 'What is the format of the exam?', NULL, 'Written only', 'Oral only', 'Both written and oral', 'Multiple choice', 'c'),
('listening', 2, 125, 'What does the professor recommend?', NULL, 'Starting early', 'Forming study groups', 'Reviewing old exams', 'All of the above', 'd'),
('listening', 2, 126, 'What materials are allowed?', NULL, 'Open book', 'Notes only', 'Nothing', 'Calculator only', 'c'),
('listening', 2, 127, 'How does the student feel?', NULL, 'Confident', 'Nervous', 'Prepared', 'Overwhelmed', 'b'),
('listening', 2, 128, 'What will happen if the student fails?', NULL, 'Retake immediately', 'Retake next semester', 'Leave the program', 'Depends on circumstances', 'd'),
('listening', 2, 129, 'What is being discussed?', NULL, 'Teaching assistant duties', 'Grading policies', 'Course preparation', 'Student evaluations', 'a'),
('listening', 2, 130, 'What is the student''s responsibility?', NULL, 'Leading discussions', 'Grading assignments', 'Holding office hours', 'All of the above', 'd'),

-- Part C: Talks and Lectures (131-200)
('listening', 3, 131, 'What is the lecture mainly about?', NULL, 'Ancient civilizations', 'Archaeological methods', 'Historical artifacts', 'Cultural anthropology', 'b'),
('listening', 3, 132, 'According to the professor, what is the primary method?', NULL, 'Carbon dating', 'Excavation', 'Documentation', 'Analysis', 'a'),
('listening', 3, 133, 'Why does the professor mention pottery?', NULL, 'To give an example', 'To illustrate dating', 'To describe artifacts', 'To explain preservation', 'b'),
('listening', 3, 134, 'What can be inferred about ancient sites?', NULL, 'They are well preserved', 'They are difficult to locate', 'They provide valuable information', 'They are mostly destroyed', 'c'),
('listening', 3, 135, 'What will the class do next?', NULL, 'Visit a museum', 'Analyze artifacts', 'Write a paper', 'Watch a video', 'a'),
('listening', 3, 136, 'What is the main topic of the lecture?', NULL, 'Economic theories', 'Market structures', 'Supply and demand', 'International trade', 'c'),
('listening', 3, 137, 'According to the professor, what affects prices?', NULL, 'Production costs only', 'Consumer preferences only', 'Both supply and demand', 'Government regulations', 'c'),
('listening', 3, 138, 'What example does the professor give?', NULL, 'Housing market', 'Stock market', 'Labor market', 'Agricultural market', 'a'),
('listening', 3, 139, 'What is equilibrium?', NULL, 'Maximum price', 'Minimum price', 'Balance point', 'Average price', 'c'),
('listening', 3, 140, 'What will be covered next class?', NULL, 'Elasticity', 'Competition', 'Monopolies', 'Trade', 'a'),
('listening', 3, 141, 'What is the lecture about?', NULL, 'Plant biology', 'Photosynthesis', 'Cellular respiration', 'Ecology', 'b'),
('listening', 3, 142, 'What do plants produce?', NULL, 'Carbon dioxide', 'Oxygen', 'Nitrogen', 'Hydrogen', 'b'),
('listening', 3, 143, 'What is required for photosynthesis?', NULL, 'Sunlight only', 'Water only', 'Both sunlight and water', 'Oxygen', 'c'),
('listening', 3, 144, 'Where does photosynthesis occur?', NULL, 'Roots', 'Stems', 'Leaves', 'Flowers', 'c'),
('listening', 3, 145, 'What is chlorophyll?', NULL, 'A nutrient', 'A pigment', 'A protein', 'An enzyme', 'b'),
('listening', 3, 146, 'What is the professor''s main point?', NULL, 'Process is complex', 'Process is essential', 'Process is efficient', 'All of the above', 'd'),
('listening', 3, 147, 'What is the lecture mainly about?', NULL, 'Literary movements', 'Famous authors', 'Writing techniques', 'Poetry analysis', 'a'),
('listening', 3, 148, 'What characterized Romanticism?', NULL, 'Emotion and nature', 'Reason and logic', 'Social realism', 'Experimental form', 'a'),
('listening', 3, 149, 'Who were key Romantic poets?', NULL, 'Shakespeare and Milton', 'Wordsworth and Coleridge', 'Eliot and Pound', 'Frost and Whitman', 'b'),
('listening', 3, 150, 'What followed Romanticism?', NULL, 'Modernism', 'Realism', 'Classicism', 'Postmodernism', 'b'),
('listening', 3, 151, 'What assignment will students complete?', NULL, 'Write a poem', 'Analyze a poem', 'Research a poet', 'Compare movements', 'b'),
('listening', 3, 152, 'What is the topic of the talk?', NULL, 'Space exploration', 'Planetary science', 'Astronomy basics', 'Rocket technology', 'a'),
('listening', 3, 153, 'What was a major achievement?', NULL, 'Moon landing', 'Mars rover', 'Space station', 'Satellite launch', 'a'),
('listening', 3, 154, 'What is a current goal?', NULL, 'Return to Moon', 'Mars colonization', 'Asteroid mining', 'Deep space travel', 'b'),
('listening', 3, 155, 'What is a major challenge?', NULL, 'Technology', 'Funding', 'Distance', 'All of the above', 'd'),
('listening', 3, 156, 'What does the speaker emphasize?', NULL, 'International cooperation', 'Private sector involvement', 'Scientific advancement', 'All of the above', 'd'),
('listening', 3, 157, 'What is the lecture about?', NULL, 'Art history', 'Renaissance art', 'Modern art', 'Abstract art', 'b'),
('listening', 3, 158, 'What defined the Renaissance?', NULL, 'Religious themes', 'Humanist perspective', 'Abstract forms', 'Social criticism', 'b'),
('listening', 3, 159, 'Who were major Renaissance artists?', NULL, 'Picasso and Dali', 'Monet and Renoir', 'Da Vinci and Michelangelo', 'Van Gogh and Gauguin', 'c'),
('listening', 3, 160, 'What technique was developed?', NULL, 'Perspective', 'Impressionism', 'Cubism', 'Surrealism', 'a'),
('listening', 3, 161, 'What will students study next?', NULL, 'Baroque period', 'Medieval art', 'Modern art', 'Contemporary art', 'a'),
('listening', 3, 162, 'What is the main topic?', NULL, 'Genetics', 'Evolution', 'DNA structure', 'Heredity', 'c'),
('listening', 3, 163, 'What does DNA stand for?', NULL, 'Deoxyribonucleic acid', 'Dynamic nucleic acid', 'Double nuclear acid', 'Deoxyribose acid', 'a'),
('listening', 3, 164, 'What is DNA''s shape?', NULL, 'Single helix', 'Double helix', 'Triple helix', 'Linear', 'b'),
('listening', 3, 165, 'What are the building blocks?', NULL, 'Amino acids', 'Nucleotides', 'Proteins', 'Lipids', 'b'),
('listening', 3, 166, 'What does DNA contain?', NULL, 'Genetic information', 'Energy', 'Nutrients', 'Enzymes', 'a'),
('listening', 3, 167, 'What process will be covered next?', NULL, 'Replication', 'Transcription', 'Translation', 'All of the above', 'd'),
('listening', 3, 168, 'What is the lecture about?', NULL, 'Political systems', 'Democracy', 'Elections', 'Government structure', 'b'),
('listening', 3, 169, 'What is a key principle?', NULL, 'Majority rule', 'Minority rights', 'Both A and B', 'Military power', 'c'),
('listening', 3, 170, 'What are forms of democracy?', NULL, 'Direct and representative', 'Authoritarian and liberal', 'Federal and unitary', 'Presidential and parliamentary', 'a'),
('listening', 3, 171, 'What is required for democracy?', NULL, 'Free elections', 'Rule of law', 'Civil liberties', 'All of the above', 'd'),
('listening', 3, 172, 'What will be discussed next?', NULL, 'Historical development', 'Contemporary challenges', 'Comparative systems', 'Electoral processes', 'b'),
('listening', 3, 173, 'What is the topic?', NULL, 'Computer programming', 'Artificial intelligence', 'Machine learning', 'Data science', 'c'),
('listening', 3, 174, 'How do machines learn?', NULL, 'Through programming', 'From data patterns', 'By trial and error', 'From human input', 'b'),
('listening', 3, 175, 'What is supervised learning?', NULL, 'Learning with labeled data', 'Learning without guidance', 'Learning by reinforcement', 'Learning by observation', 'a'),
('listening', 3, 176, 'What are applications?', NULL, 'Image recognition', 'Speech processing', 'Recommendation systems', 'All of the above', 'd'),
('listening', 3, 177, 'What is a limitation?', NULL, 'Requires large datasets', 'Expensive to implement', 'Difficult to understand', 'All of the above', 'a'),
('listening', 3, 178, 'What will be covered next?', NULL, 'Neural networks', 'Deep learning', 'Algorithms', 'Applications', 'b'),
('listening', 3, 179, 'What is the lecture about?', NULL, 'Marketing strategies', 'Consumer behavior', 'Brand management', 'Advertising', 'b'),
('listening', 3, 180, 'What influences purchasing decisions?', NULL, 'Price only', 'Quality only', 'Multiple factors', 'Brand loyalty', 'c'),
('listening', 3, 181, 'What is the decision-making process?', NULL, 'Two stages', 'Three stages', 'Five stages', 'Seven stages', 'c'),
('listening', 3, 182, 'What are psychological factors?', NULL, 'Motivation and perception', 'Income and education', 'Age and gender', 'Culture and society', 'a'),
('listening', 3, 183, 'What will students analyze?', NULL, 'Case studies', 'Market research', 'Advertising campaigns', 'Consumer surveys', 'a'),
('listening', 3, 184, 'What is the main topic?', NULL, 'Nutrition', 'Exercise physiology', 'Public health', 'Disease prevention', 'c'),
('listening', 3, 185, 'What is public health concerned with?', NULL, 'Individual treatment', 'Population health', 'Medical research', 'Hospital care', 'b'),
('listening', 3, 186, 'What are prevention levels?', NULL, 'Primary and secondary', 'Primary, secondary, tertiary', 'Early and late', 'Individual and community', 'b'),
('listening', 3, 187, 'What is an example of primary prevention?', NULL, 'Vaccination', 'Screening', 'Treatment', 'Rehabilitation', 'a'),
('listening', 3, 188, 'What factors affect health?', NULL, 'Biological only', 'Social only', 'Biological and social', 'Environmental only', 'c'),
('listening', 3, 189, 'What will be discussed next?', NULL, 'Epidemiology', 'Health policy', 'Disease outbreaks', 'Healthcare systems', 'a'),
('listening', 3, 190, 'What is the lecture about?', NULL, 'Urban planning', 'Architecture', 'City development', 'Transportation', 'a'),
('listening', 3, 191, 'What is sustainable urban planning?', NULL, 'Low-cost development', 'Environmentally friendly design', 'High-density housing', 'Modern architecture', 'b'),
('listening', 3, 192, 'What are key considerations?', NULL, 'Transportation', 'Green spaces', 'Mixed-use development', 'All of the above', 'd'),
('listening', 3, 193, 'What is a challenge?', NULL, 'Population growth', 'Limited resources', 'Political issues', 'All of the above', 'd'),
('listening', 3, 194, 'What example is given?', NULL, 'Copenhagen', 'New York', 'Tokyo', 'London', 'a'),
('listening', 3, 195, 'What is the topic?', NULL, 'Music history', 'Music theory', 'Musical instruments', 'Classical composers', 'a'),
('listening', 3, 196, 'What period is discussed?', NULL, 'Medieval', 'Baroque', 'Classical', 'Romantic', 'b'),
('listening', 3, 197, 'Who were major composers?', NULL, 'Bach and Handel', 'Mozart and Beethoven', 'Brahms and Wagner', 'Debussy and Ravel', 'a'),
('listening', 3, 198, 'What characterized the music?', NULL, 'Simple melodies', 'Ornamentation', 'Minimalism', 'Electronic sounds', 'b'),
('listening', 3, 199, 'What will students listen to?', NULL, 'Modern music', 'Baroque pieces', 'Folk music', 'Jazz', 'b'),
('listening', 3, 200, 'What is the assignment?', NULL, 'Compose music', 'Analyze a piece', 'Research a composer', 'Attend a concert', 'b');
